# -*- coding: utf-8 -*-
"""GWI_interview_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KzY7MtJMY8oP11F9OZbmVJNccoLDZ5YQ
"""

import numpy as np
import pandas as pd
import matplotlib as plt

raw_df

df_q7_long

[f'q4_{i}' for i in range(1, 5)]

cross_tab = df_q7_long.groupby(['question_base', 'question_id']).size().reset_index(name='count')
print(cross_tab)

labels_df = pd.read_csv('labels.csv')
labels_df

labels_df.columns

labels_df['Question ID'].unique()

labels_df['Question Code'].unique()

labels_df['Question'].unique()

col_groups = {
    code: group_df
    for code, group_df in labels_df.groupby('Question Code')
}
col_groups['s2']

col_groups['q2']

col_groups['q7']

col_groups['q7'].groupby('Base option')['Subcode'].agg(
    total_responses='count',
    null_responses=lambda x: x.isnull().sum()
)

for code in labels_df['Question Code'].unique():
  print(col_groups[code])

labels_df.isnull().sum().sort_values(ascending=False)

labels_df[labels_df.isnull().any(axis=1)]

null_counts = labels_df[labels_df['Option suffix'].isnull()].groupby('Question Code').size()
print(null_counts)

null_counts = labels_df[labels_df['Subcode'].isnull()].groupby('Question Code').size()
print(null_counts)

null_counts = labels_df[labels_df['Subcode'].isnull()].groupby('Question').size()
print(null_counts)

null_counts = labels_df[labels_df['Subcode'].isnull()].groupby('Question ID').size()
print(null_counts)

#labels_df[labels_df.isnull().any(axis=1)]
# Filter rows with null answer_code
null_entries = labels_df[labels_df['Subcode'].isnull()]
# Group by question_code and display
for question, group in null_entries.groupby('Question'):
    print(f"\n=== Null Responses for Question: {question} ===")
    display(group)

raw_df = pd.read_csv('live_test.csv')
raw_df

q7_cols = [col for col in raw_df.columns if col.startswith('q7_')]
long_q7 = raw_df.melt(id_vars='respondent_id', value_vars=q7_cols,
                       var_name='question_id', value_name='response')
long_q7

#labels_df[labels_df.isnull().any(axis=1)]
# Filter rows with null answer_code
null_entries = long_q7[long_q7.isnull()]
# Group by question_code and display
for question, group in null_entries.groupby('question_id'):
    print(f"\n=== Null Responses for Question: {question} ===")
    display(group)

long_q7.groupby('question_id').agg('count')

df_q7_long

df_q7_long.groupby('question_id')['question_base'].agg('count')

df_q7_long.groupby('question_id').agg('count')

raw_df.columns

raw_df.info()

def get_country(df):
    country_cols = [col for col in df.columns if col.startswith("s2_")]
    return df[country_cols].idxmax(axis=1).map(lambda x: x.split('_')[1])

get_country(raw_df)

raw_df[(raw_df['q2_1'] == 1)].shape

raw_df['gender'].value_counts()[[0]] #.plot(kind='bar')

df_q7_long
df_q7_long_mapped

#df.groupby(['gender', 'age_group']).size().reset_index(name='count')

raw_df.groupby('gender')['total_selected_q7'].mean()

df[df.duplicated(subset=['respondent_id'], keep=False)].groupby('respondent_id').size()

df[df.duplicated()]['respondent_id']

df[df.duplicated(keep='last')]['respondent_id']

df.loc[df.duplicated(keep=False)]

df[df.duplicated(keep=False)]

df[df.duplicated()]

raw_df.duplicated().sum()

raw_df['q7_1'].hist(bins=10)

df_q7_long.groupby(['question_base','question_id']).agg('count')

df_q7_long.groupby(['question_id','question_base']).agg('count')

df.groupby(['gender', 'q7_1']).size().reset_index(name='count')

raw_df['total_selected_q7'].value_counts()

raw_df['total_selected_q7'] = raw_df[['q7_1', 'q7_2', 'q7_3', 'q7_4', 'q7_5']].apply(lambda row: sum(row != 8), axis=1)
raw_df

raw_df['gender'] = np.select(
    [raw_df['q2_1'] == 1, raw_df['q2_2'] == 1],
    ['Male', 'Female'],
    default='Unknown'
)
raw_df

raw_df[(raw_df['q2_1'] == 1) & (raw_df['q7_1'] != 8)].shape

# Filter with regex
gender_cols = raw_df.filter(regex='^q2_').columns
df[gender_cols]

raw_df.filter(like='q7_')

raw_df.columns.tolist()

raw_df['q7_1'].value_counts(dropna=False)

raw_df.isnull().sum().sort_values(ascending=False)

raw_df[raw_df.isnull().any(axis=1)]

labels_dict = labels_df.set_index('Question ID')['Base option'].to_dict()
labels_dict

question_map = labels_df.groupby('Question Code')[['Question']].first()
question_map
question_map[question_map.index=='q7']

question_map = labels_df.groupby('Question Code')[['Question', 'Question Code']].first()
question_map

df= raw_df
q7_cols = [col for col in df.columns if col.startswith('q7_')]
df_q7 = df[['respondent_id'] + q7_cols]
df_q7

df_q7_long = df_q7.melt(id_vars='respondent_id',
                        var_name='question_id',
                        value_name='selected')
df_q7_long

df_q7_long[df_q7_long['selected'] == 1].shape[0] / df_q7_long.shape[0]

df_q7_long[df_q7_long['selected'] == 1]

df_q7_long['description'] = df_q7_long['question_id'].map(labels_dict)
df_q7_long

gender_map = {'q2_1': 'Male', 'q2_2': 'Female'}
df_gender = df[['respondent_id', 'q2_1', 'q2_2']].melt('respondent_id')
df_gender

gender_map = {'q2_1': 'Male', 'q2_2': 'Female'}
df_gender = df[['respondent_id', 'q2_1', 'q2_2']].melt('respondent_id')
df_gender = df_gender[df_gender['value'] == 1]
df_gender['gender'] = df_gender['variable'].map(gender_map)
df_gender

country_cols = [col for col in df.columns if col.startswith('s2_')]
df['country'] = df[country_cols].idxmax(axis=1).map(labels_dict)
df['country'].value_counts()

country_cols = [col for col in df.columns if col.startswith('s2_')]
df['country'] = df[country_cols].idxmax(axis=1).map(labels_dict)
df['country'].value_counts().plot(kind='barh')

df[q7_cols]

df[q7_cols].values

df[q7_cols].values.shape

df[q7_cols].values.reshape(5, -1)

df[q7_cols].values.reshape(5, -1).shape

q7_matrix = df[q7_cols].replace({8: np.nan})
q7_matrix

q7_matrix.isna()
q7_matrix.isna().mean()

q7_matrix.isna().mean().values

q7_matrix.isna().mean().values.reshape(5, -1).shape

q7_matrix.isna().mean().values.reshape(5, -1)

q7_matrix.isna().mean().values.reshape(5, -1).shape

import seaborn as sns
q7_matrix = df[q7_cols].replace({8: np.nan})  # replace 'None' with NaN
sns.heatmap(q7_matrix.isna().mean().values.reshape(5, -1), cmap="coolwarm")

country_cols = [col for col in df.columns if col.startswith('s2_')]
country_cols

df[country_cols]

df[country_cols][109:110]

df[country_cols].loc[109]

df[country_cols].idxmax()

df[country_cols].idxmax(axis=1)

country_cols = [col for col in df.columns if col.startswith('s2_')]
df['country'] = df[country_cols].idxmax(axis=1).map(labels_dict)
df

df['country'].value_counts()

q7_cols = [col for col in df.columns if col.startswith('q7_')]
df_q7_long = df[['respondent_id'] + q7_cols].melt('respondent_id')
df_q7_long = df_q7_long[df_q7_long['value'] != 0]
df_q7_long['label'] = df_q7_long['variable'].map(labels_dict)
df_q7_long

set(labels_df['Question ID']).intersection(set(raw_df.columns))

missing_cols = set(labels_df['Question ID']) - set(raw_df.columns)
missing_cols

extra_cols = set(raw_df.columns) - set(labels_df['Question ID']) - {'respondent_id'}
extra_cols

raw_df[labels_df['Question ID'].unique()].apply(pd.Series.value_counts).T.fillna(0)

raw_df['q7_5'].value_counts()

raw_df['q7_1'].value_counts(dropna=False)

def extract_country(row):
    for col in row.index:
        if col.startswith('s2_') and row[col] == 1:
            return labels_df.loc[labels_df['Question ID'] == col, 'Base option'].values[0]
    return None
raw_df['country'] = raw_df.apply(extract_country, axis=1)
raw_df['country']

def extract_country(row):
    for col in row.index:
        if col.startswith('s2_') and row[col] == 1:
            return labels_df.loc[labels_df['Question ID'] == col, 'Base option'].values[0]
    return None
raw_df['country'] = raw_df.apply(extract_country, axis=1)
raw_df['country'].value_counts()

raw_df[['q2_1', 'q2_2']]

raw_df[['q2_1', 'q2_2']].idxmax(axis=1)

raw_df[['q2_1', 'q2_2']].idxmax(axis=1).str[-1]

raw_df[['q2_1', 'q2_2']].idxmax(axis=1).str[-1].map({'1': 'Male', '2': 'Female'})

raw_df['gender'] = raw_df[['q2_1', 'q2_2']].idxmax(axis=1).str[-1].map({'1': 'Male', '2': 'Female'})
raw_df['gender'].value_counts()

age_cols = [col for col in raw_df.columns if col.startswith('q3_')]
raw_df[age_cols].sum().sort_index()  # Should match 18–64

# Area type
raw_df['area'] = raw_df[['q48_1', 'q48_2', 'q48_3']].idxmax(axis=1).str[-1].map({
    '1': 'Urban', '2': 'Suburban', '3': 'Rural'
})
raw_df['area'].value_counts()

raw_df['area']

q7_cols = [col for col in raw_df.columns if col.startswith('q7_')]
q7_cols

q7_cols = [col for col in raw_df.columns if col.startswith('q7_')]
raw_df[q7_cols]

long_q7 = raw_df.melt(id_vars='respondent_id', value_vars=q7_cols,
                       var_name='question_id', value_name='response')
long_q7

long_q7 = raw_df.melt(id_vars='respondent_id', value_vars=q7_cols,
                       var_name='question_id', value_name='response')
long_q7 = long_q7.merge(labels_df[['Question ID', 'Base option', 'Option suffix']],
                        left_on='question_id', right_on='Question ID', how='left')
long_q7

long_q7['Option suffix'].value_counts()  # Most used platforms

long_q7['Base option'].value_counts()    # Most common purposes

text_cols = [col for col in raw_df.columns if "_TEXT" in col]
raw_df[text_cols].isnull().mean()  # % missing

def summarize_columns(df):
    return pd.DataFrame({
        'null_pct': df.isnull().mean(),
        'n_unique': df.nunique(),
        'most_freq': df.mode().iloc[0]
    })

summarize_columns(raw_df).sort_values(by='null_pct', ascending=False).head(10)

q7_cols = [col for col in raw_df.columns if col.startswith('q7_') and col.count('_') == 2]  # get q7_1_1, ..., q7_5_8
long_q7 = raw_df.melt(id_vars='respondent_id', value_vars=q7_cols,
                      var_name='question_id', value_name='response')
long_q7 = long_q7[long_q7['response'] != 0]

# Merge labels
long_q7 = long_q7.merge(labels_df[['Question ID', 'Base option', 'Option suffix']],
                        left_on='question_id', right_on='Question ID', how='left')
long_q7

# First, identify q7 base columns
q7_base_cols = [col for col in raw_df.columns if col.startswith('q7_') and col.count('_') == 1]

# Melt the collapsed format (each cell contains a numeric code)
df_q7_long = raw_df.melt(id_vars='respondent_id', value_vars=q7_base_cols,
                         var_name='question_base', value_name='precode')
df_q7_long

# Create the equivalent question_id as in labels_df
# e.g., q7_1 + 3 → q7_1_3
df_q7_long['question_id'] = df_q7_long.apply(
    lambda row: f"{row['question_base']}_{int(row['precode'])}", axis=1
)

df_q7_long_mapped= df_q7_long
df_q7_long_mapped

df_q7_long_mapped

labels_dict

df_q7_long_mapped['description'] = df_q7_long_mapped['question_id'].map(labels_dict)
df_q7_long_mapped

df_q7_long_mapped['description'].value_counts()

df_q7_long_mapped.groupby('description').value_counts()

df_q7_long_mapped.groupby('description').nunique()

# First, identify q7 base columns
q7_base_cols = [col for col in raw_df.columns if col.startswith('q7_') and col.count('_') == 1]

# Melt the collapsed format (each cell contains a numeric code)
df_q7_long = raw_df.melt(id_vars='respondent_id', value_vars=q7_base_cols,
                         var_name='question_base', value_name='precode')

# Remove missing or zero/invalid responses
df_q7_long = df_q7_long[df_q7_long['precode'].notnull() & (df_q7_long['precode'] != 0)]

# Create the equivalent question_id as in labels_df
# e.g., q7_1 + 3 → q7_1_3
df_q7_long['question_id'] = df_q7_long.apply(
    lambda row: f"{row['question_base']}_{int(row['precode'])}", axis=1
)

# Now merge with the labels
df_q7_long = df_q7_long.merge(
    labels_df[['Question ID', 'Base option', 'Option suffix']],
    left_on='question_id', right_on='Question ID',
    how='left'
)

df_q7_long[['respondent_id', 'question_id', 'Base option', 'Option suffix']]

